FROM prestashop/prestashop

ENV PS_LANGUAGE=ES
ENV PS_ENABLE_SSL=1

# Container name of the DB (declared inside docker-compose.yml)
ENV DB_SERVER={database_container_name}
ENV DB_PASSWD={database_password}